// pm2 ecosystem config — generated by `surfacemcp init`
// Run: pm2 start ecosystem.config.cjs && pm2 save
module.exports = {
  apps: [
    {
      name: 'surfacemcp-kanbanmcp',
      script: '/usr/bin/surfacemcp',
      args: 'serve',
      cwd: '/root/kanbanmcp',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        SURFACEMCP_CONFIG: '/root/kanbanmcp/surfacemcp.config.json',
      },
      out_file: '/root/kanbanmcp/.surfacemcp/logs/out.log',
      error_file: '/root/kanbanmcp/.surfacemcp/logs/err.log',
      merge_logs: true,
      autorestart: true,
      watch: false,
    },
  ],
};
